In [1]:
import pandas as pd

In [2]:
school=pd.read_csv('C:\\Users\\bharg\\Desktop\\Bhargav\student-enrollment.csv')
school

,State,Enrolment - All Types of Management - Total (Pre-primary to 12),Enrolment - All Types of Management - Pre- Primary,Enrolment - All Types of Management - Primary (1 to 5),Enrolment - All Types of Management - Upper Primary (6-8),Enrolment - All Types of Management - Elementary (1-8),Enrolment - All Types of Management - Secondary (9-10),Enrolment - All Types of Management - Higher Secondary (11-12)
0,Andaman and Nicobar Islands,73861,6885,25964,17719,43683,11810,11483
1,Andhra Pradesh,8244647,77391,3724793,2169034,5893827,1341250,932179
2,Arunachal Pradesh,354382,26076,164061,84930,248991,45455,33860
3,Assam,7544960,443388,3645363,1905775,5551138,1004682,545752
4,Bihar,27472692,426254,14179532,7253543,21433075,3618298,1995065
5,Chandigarh,268627,22059,95948,64102,160050,43795,42723
6,Chhattisgarh,5992197,227967,2692513,1486418,4178931,840172,745127
7,Dadra and Nagar Haveli and Daman and Diu,133358,5111,59586,35350,94936,18671,14640
8,Delhi,4572107,253625,1754430,1190775,2945205,725275,648002
9,Goa,304982,22556,121356,72310,193666,46866,41894
10,Gujarat,11542276,164691,5387190,3090985,8478175,1750516,1148894
11,Haryana,6035679,243645,2579262,1480339,4059601,952143,780290
12,Himachal Pradesh,1437022,104874,550993,342695,893688,216429,222031
13,Jammu and Kashmir,2718644,395249,1106932,577505,1684437,344485,294473
14,Jharkhand,7970750,282543,3740909,2114309,5855218,1089069,743920
15,Karnataka,12092381,265028,5456226,3196946,8653172,1970316,1203865
16,Kerala,6423120,568172,2486240,1501003,3987243,996090,871615
17,Ladakh,59788,10718,22892,12166,35058,7582,6430
18,Lakshadweep,13586,1582,5395,2813,8208,1873,1923
19,Madhya Pradesh,16169265,741979,7357389,4224219,11581608,2196508,1649170
20,Maharashtra,22586695,525861,9565321,5855597,15420918,3735647,2904269
21,Manipur,693194,61723,310023,150863,460886,91005,79580
22,Meghalaya,1169720,214782,530390,244008,774398,117496,63044
23,Mizoram,309904,32567,136649,71949,208598,40605,28134
24,Nagaland,443796,76621,177955,96439,274394,58721,34060
25,Odisha,7576893,49376,3519153,2071755,5590908,1246381,690228
26,Puducherry,255546,22518,95088,60767,155855,41002,36171
27,Punjab,6147500,795454,2324297,1374962,3699259,867890,784897
28,Rajasthan,17667510,492507,8256720,4308249,12564969,2420574,2189460
29,Sikkim,135963,19634,45890,29469,75359,23151,17819
30,Tamil Nadu,12830951,663651,5158880,3115298,8274178,2080142,1812980
31,Telangana,6915241,151592,3041318,1801218,4842536,1118377,802736
32,Tripura,713862,29683,312398,179559,491957,110536,81686
33,Uttar Pradesh,47181438,407034,24182635,11590094,35772729,6223321,4778354
34,Uttarakhand,2449926,94158,1061894,595782,1657676,365696,332396
35,West Bengal,18733367,1568253,7966665,4421747,12388412,2766802,2009900

In [3]:
school.duplicated().sum()

0

In [4]:
school.isnull().sum()

State                                                              0
Enrolment - All Types of Management - Total (Pre-primary to 12)    0
Enrolment - All Types of Management - Pre- Primary                 0
Enrolment - All Types of Management - Primary (1 to 5)             0
Enrolment - All Types of Management - Upper Primary (6-8)          0
Enrolment - All Types of Management - Elementary (1-8)             0
Enrolment - All Types of Management - Secondary (9-10)             0
Enrolment - All Types of Management - Higher Secondary (11-12)     0
dtype: int64

In [5]:
# the school dataset doesnot have null values

In [6]:
numerical=[fea for fea in school.columns if school[fea].dtypes!=object]
numerical

['Enrolment - All Types of Management - Total (Pre-primary to 12)',
 'Enrolment - All Types of Management - Pre- Primary',
 'Enrolment - All Types of Management - Primary (1 to 5)',
 'Enrolment - All Types of Management - Upper Primary (6-8)',
 'Enrolment - All Types of Management - Elementary (1-8)',
 'Enrolment - All Types of Management - Secondary (9-10)',
 'Enrolment - All Types of Management - Higher Secondary (11-12)']

In [7]:
categorical=[fea for fea in school.columns if school[fea].dtypes==object]
categorical

['State']

In [8]:
school_numerical_data=school[numerical]
school_numerical_data

,Enrolment - All Types of Management - Total (Pre-primary to 12),Enrolment - All Types of Management - Pre- Primary,Enrolment - All Types of Management - Primary (1 to 5),Enrolment - All Types of Management - Upper Primary (6-8),Enrolment - All Types of Management - Elementary (1-8),Enrolment - All Types of Management - Secondary (9-10),Enrolment - All Types of Management - Higher Secondary (11-12)
0,73861,6885,25964,17719,43683,11810,11483
1,8244647,77391,3724793,2169034,5893827,1341250,932179
2,354382,26076,164061,84930,248991,45455,33860
3,7544960,443388,3645363,1905775,5551138,1004682,545752
4,27472692,426254,14179532,7253543,21433075,3618298,1995065
5,268627,22059,95948,64102,160050,43795,42723
6,5992197,227967,2692513,1486418,4178931,840172,745127
7,133358,5111,59586,35350,94936,18671,14640
8,4572107,253625,1754430,1190775,2945205,725275,648002
9,304982,22556,121356,72310,193666,46866,41894
10,11542276,164691,5387190,3090985,8478175,1750516,1148894
11,6035679,243645,2579262,1480339,4059601,952143,780290
12,1437022,104874,550993,342695,893688,216429,222031
13,2718644,395249,1106932,577505,1684437,344485,294473
14,7970750,282543,3740909,2114309,5855218,1089069,743920
15,12092381,265028,5456226,3196946,8653172,1970316,1203865
16,6423120,568172,2486240,1501003,3987243,996090,871615
17,59788,10718,22892,12166,35058,7582,6430
18,13586,1582,5395,2813,8208,1873,1923
19,16169265,741979,7357389,4224219,11581608,2196508,1649170
20,22586695,525861,9565321,5855597,15420918,3735647,2904269
21,693194,61723,310023,150863,460886,91005,79580
22,1169720,214782,530390,244008,774398,117496,63044
23,309904,32567,136649,71949,208598,40605,28134
24,443796,76621,177955,96439,274394,58721,34060
25,7576893,49376,3519153,2071755,5590908,1246381,690228
26,255546,22518,95088,60767,155855,41002,36171
27,6147500,795454,2324297,1374962,3699259,867890,784897
28,17667510,492507,8256720,4308249,12564969,2420574,2189460
29,135963,19634,45890,29469,75359,23151,17819
30,12830951,663651,5158880,3115298,8274178,2080142,1812980
31,6915241,151592,3041318,1801218,4842536,1118377,802736
32,713862,29683,312398,179559,491957,110536,81686
33,47181438,407034,24182635,11590094,35772729,6223321,4778354
34,2449926,94158,1061894,595782,1657676,365696,332396
35,18733367,1568253,7966665,4421747,12388412,2766802,2009900

In [9]:
school_categorical_data=school[categorical]
school_categorical_data

                                       State
0                Andaman and Nicobar Islands
1                             Andhra Pradesh
2                          Arunachal Pradesh
3                                      Assam
4                                      Bihar
5                                 Chandigarh
6                               Chhattisgarh
7   Dadra and Nagar Haveli and Daman and Diu
8                                      Delhi
9                                        Goa
10                                   Gujarat
11                                   Haryana
12                          Himachal Pradesh
13                         Jammu and Kashmir
14                                 Jharkhand
15                                 Karnataka
16                                    Kerala
17                                    Ladakh
18                               Lakshadweep
19                            Madhya Pradesh
20                               Maharashtra
21                                   Manipur
22                                 Meghalaya
23                                   Mizoram
24                                  Nagaland
25                                    Odisha
26                                Puducherry
27                                    Punjab
28                                 Rajasthan
29                                    Sikkim
30                                Tamil Nadu
31                                 Telangana
32                                   Tripura
33                             Uttar Pradesh
34                               Uttarakhand
35                               West Bengal

In [10]:
from sklearn.decomposition import PCA

In [11]:
p=PCA()

In [12]:
p.fit(school_numerical_data)

PCA()

In [13]:
a=p.transform(school_numerical_data)
a

array([[-9.82622899e+06, -3.10473879e+05, -3.33017628e+04,
        -4.20223124e+04, -6.11519649e+03, -2.39766471e-09,
        -3.17827778e-11],
       [ 1.20641239e+06,  4.04089900e+04, -2.68655990e+05,
         8.72103616e+04, -3.92281691e+04,  3.70641323e-10,
         2.47560548e-10],
       [-9.44393168e+06, -3.06904227e+05, -1.69355586e+04,
        -4.12869517e+04, -5.73185477e+03, -1.86327345e-09,
         7.53995269e-11],
       [ 3.77999015e+05, -2.15922129e+05,  3.02008329e+05,
         1.24810134e+05, -2.80992470e+04,  7.33705041e-11,
         2.80149022e-10],
       [ 2.85987250e+07, -1.33162494e+06,  3.00468489e+05,
         5.64801499e+05,  1.42457351e+04,  8.13143899e-09,
         8.81525339e-11],
       [-9.58230675e+06, -2.75148226e+05, -3.33157844e+04,
        -4.44019819e+04, -4.76579499e+03, -1.33480246e-09,
        -2.44876876e-10],
       [-1.91772684e+06,  3.41440542e+04, -2.82896379e+04,
        -8.30716249e+04,  4.82333562e+04, -5.13686621e-10,
         2.42924646e-10],
       [-9.73901094e+06, -3.17712944e+05, -3.40007149e+04,
        -3.93953954e+04, -4.90713327e+03, -2.02264397e-09,
         1.33044582e-10],
       [-4.02788516e+06,  2.90776446e+05, -8.33111488e+04,
         3.73791613e+03,  6.37662814e+04, -8.55561427e-10,
         3.39310594e-11],
       [-9.52678315e+06, -2.83921604e+05, -2.96564435e+04,
        -4.42207259e+04, -6.09160873e+03, -2.41860601e-09,
         1.76589555e-10],
       [ 5.82744187e+06, -6.26340046e+04, -2.00314287e+05,
         2.17928533e+05,  1.14201562e+04,  1.37796549e-09,
         2.72773616e-10],
       [-1.97861658e+06,  2.12020407e+05, -7.96459189e+04,
        -6.31908143e+04, -1.98294559e+04, -3.94522220e-10,
         2.22581044e-10],
       [-8.08966083e+06, -1.07531288e+05, -2.52539186e+04,
        -6.52096439e+04,  1.19236062e+04, -1.97661018e-09,
         4.83361892e-11],
       [-6.46525327e+06,  6.10850758e+04,  2.39769649e+05,
        -8.20616745e+04, -6.88593124e+03, -1.37116682e-09,
         3.29259890e-10],
       [ 9.45678337e+05, -1.44568560e+05,  5.47092310e+04,
         1.27677281e+05,  7.25181735e+04,  1.70925801e-10,
         1.87046718e-10],
       [ 6.39353894e+06,  2.12291008e+05, -1.97029420e+05,
         2.71567755e+05, -9.67320941e+04,  1.87593976e-09,
         3.71741242e-10],
       [-1.75080080e+06,  6.37301588e+05,  1.35644233e+05,
        -8.84321201e+04, -3.56344444e+03, -5.71995978e-10,
         2.40743391e-10],
       [-9.84399639e+06, -3.13810140e+05, -2.67495301e+04,
        -4.24416763e+04, -7.06123417e+03, -2.44266188e-09,
        -1.03282015e-10],
       [-9.90113795e+06, -3.22432876e+05, -3.35210181e+04,
        -4.20367947e+04, -6.93116534e+03, -2.25979233e-09,
        -1.63665838e-10],
       [ 1.18756681e+07,  3.86256762e+05,  2.12680735e+05,
         2.12405383e+05,  1.99925677e+05,  2.00947922e-09,
         3.62418297e-10],
       [ 1.99554740e+07,  1.55669727e+06, -6.56113036e+05,
         1.76271647e+05, -4.26478549e+03,  4.31484684e-09,
         7.11894869e-10],
       [-9.00999865e+06, -2.65431624e+05,  4.46277974e+03,
        -5.83179852e+04, -9.62607352e+03, -2.05697673e-09,
        -2.75029374e-11],
       [-8.39422500e+06, -2.21822877e+05,  1.64227175e+05,
        -3.83115113e+04, -1.13130979e+04, -1.45761039e-09,
         1.84673894e-10],
       [-9.51119646e+06, -2.98606948e+05, -1.13954021e+04,
        -4.02240150e+04, -7.47408304e+03, -1.98733144e-09,
        -1.05720620e-10],
       [-9.35611807e+06, -2.59456928e+05,  2.39439107e+04,
        -3.59316294e+04, -1.15810970e+04, -1.80795015e-09,
        -2.47280689e-10],
       [ 4.37667271e+05, -1.67501241e+05, -2.10732479e+05,
         2.26796795e+05, -6.56168871e+04,  2.04568446e-10,
         1.92046885e-10],
       [-9.59576012e+06, -2.82209113e+05, -2.95213909e+04,
        -4.24459035e+04, -6.32779901e+03, -1.68268907e-09,
         1.31055188e-10],
       [-2.20480952e+06,  7.20714232e+05,  3.86110645e+05,
        -1.02052390e+05,  2.14339309e+04, -7.46180978e-10,
         3.20121978e-10],
       [ 1.38950565e+07,  3.76314131e+05, -7.42217803e+04,
        -3.01663756e+05,  1.14245884e+05,  2.84681220e-09,
         4.85018310e-10],
       [-9.75286251e+06, -2.93938600e+05, -2.54887059e+04,
        -4.17770059e+04, -9.16080005e+03, -1.62756783e-09,
         1.64497513e-11],
       [ 6.66374591e+06,  1.25304886e+06, -1.33308976e+05,
        -1.26070051e+05, -8.29321709e+03,  1.34961872e-09,
         6.46834204e-10],
       [-6.73234045e+05,  1.02614964e+05, -1.74936500e+05,
         5.76764747e+04, -2.19794407e+04, -1.56893748e-10,
         2.26919712e-10],
       [-8.97032853e+06, -2.73427652e+05, -3.41109410e+04,
        -3.58013740e+04, -8.38253640e+03, -2.14264631e-09,
         7.14996187e-11],
       [ 5.55458946e+07, -1.24858352e+06, -7.39376485e+04,
        -5.12547758e+05, -4.57195433e+04,  1.29466415e-08,
         2.60439779e-09],
       [-6.68670967e+06, -1.21195657e+05, -5.23616219e+04,
        -7.23678371e+04,  4.42716779e+03, -1.29089708e-09,
         8.98545197e-11],
       [ 1.45252800e+07,  1.54118519e+06,  7.42084438e+05,
         1.43991538e+04, -1.16458278e+05,  3.51553728e-09,
         1.67645627e-10]])

In [14]:
pd.DataFrame(a)

,0,1,2,3,4,5,6
0,-9.826229e+06,-3.104739e+05,-33301.762759,-42022.312435,-6115.196492,-2.397665e-09,-3.178278e-11
1,1.206412e+06,4.040899e+04,-268655.990493,87210.361608,-39228.169134,3.706413e-10,2.475605e-10
2,-9.443932e+06,-3.069042e+05,-16935.558573,-41286.951692,-5731.854772,-1.863273e-09,7.539953e-11
3,3.779990e+05,-2.159221e+05,302008.328889,124810.133711,-28099.246981,7.337050e-11,2.801490e-10
4,2.859872e+07,-1.331625e+06,300468.488854,564801.499448,14245.735085,8.131439e-09,8.815253e-11
5,-9.582307e+06,-2.751482e+05,-33315.784437,-44401.981917,-4765.794988,-1.334802e-09,-2.448769e-10
6,-1.917727e+06,3.414405e+04,-28289.637930,-83071.624945,48233.356190,-5.136866e-10,2.429246e-10
7,-9.739011e+06,-3.177129e+05,-34000.714918,-39395.395429,-4907.133266,-2.022644e-09,1.330446e-10
8,-4.027885e+06,2.907764e+05,-83311.148785,3737.916133,63766.281358,-8.555614e-10,3.393106e-11
9,-9.526783e+06,-2.839216e+05,-29656.443520,-44220.725860,-6091.608731,-2.418606e-09,1.765896e-10
10,5.827442e+06,-6.263400e+04,-200314.287024,217928.532901,11420.156229,1.377965e-09,2.727736e-10
11,-1.978617e+06,2.120204e+05,-79645.918932,-63190.814303,-19829.455898,-3.945222e-10,2.225810e-10
12,-8.089661e+06,-1.075313e+05,-25253.918581,-65209.643880,11923.606241,-1.976610e-09,4.833619e-11
13,-6.465253e+06,6.108508e+04,239769.649146,-82061.674507,-6885.931235,-1.371167e-09,3.292599e-10
14,9.456783e+05,-1.445686e+05,54709.230990,127677.280700,72518.173473,1.709258e-10,1.870467e-10
15,6.393539e+06,2.122910e+05,-197029.419570,271567.755110,-96732.094124,1.875940e-09,3.717412e-10
16,-1.750801e+06,6.373016e+05,135644.233242,-88432.120086,-3563.444445,-5.719960e-10,2.407434e-10
17,-9.843996e+06,-3.138101e+05,-26749.530111,-42441.676338,-7061.234169,-2.442662e-09,-1.032820e-10
18,-9.901138e+06,-3.224329e+05,-33521.018069,-42036.794740,-6931.165338,-2.259792e-09,-1.636658e-10
19,1.187567e+07,3.862568e+05,212680.734753,212405.383133,199925.677353,2.009479e-09,3.624183e-10
20,1.995547e+07,1.556697e+06,-656113.035733,176271.646668,-4264.785491,4.314847e-09,7.118949e-10
21,-9.009999e+06,-2.654316e+05,4462.779742,-58317.985215,-9626.073517,-2.056977e-09,-2.750294e-11
22,-8.394225e+06,-2.218229e+05,164227.175402,-38311.511330,-11313.097894,-1.457610e-09,1.846739e-10
23,-9.511196e+06,-2.986069e+05,-11395.402070,-40224.015022,-7474.083043,-1.987331e-09,-1.057206e-10
24,-9.356118e+06,-2.594569e+05,23943.910665,-35931.629438,-11581.096975,-1.807950e-09,-2.472807e-10
25,4.376673e+05,-1.675012e+05,-210732.478669,226796.794641,-65616.887097,2.045684e-10,1.920469e-10
26,-9.595760e+06,-2.822091e+05,-29521.390863,-42445.903549,-6327.799009,-1.682689e-09,1.310552e-10
27,-2.204810e+06,7.207142e+05,386110.645013,-102052.390096,21433.930893,-7.461810e-10,3.201220e-10
28,1.389506e+07,3.763141e+05,-74221.780296,-301663.755722,114245.883901,2.846812e-09,4.850183e-10
29,-9.752863e+06,-2.939386e+05,-25488.705873,-41777.005872,-9160.800048,-1.627568e-09,1.644975e-11
30,6.663746e+06,1.253049e+06,-133308.975644,-126070.051118,-8293.217085,1.349619e-09,6.468342e-10
31,-6.732340e+05,1.026150e+05,-174936.500162,57676.474668,-21979.440670,-1.568937e-10,2.269197e-10
32,-8.970329e+06,-2.734277e+05,-34110.940983,-35801.374003,-8382.536396,-2.142646e-09,7.149962e-11
33,5.554589e+07,-1.248584e+06,-73937.648540,-512547.757925,-45719.543298,1.294664e-08,2.604398e-09
34,-6.686710e+06,-1.211957e+05,-52361.621861,-72367.837144,4427.167791,-1.290897e-09,8.985452e-11
35,1.452528e+07,1.541185e+06,742084.437697,14399.153849,-116458.278417,3.515537e-09,1.676456e-10

In [15]:
pd.DataFrame(p.explained_variance_ratio_)

              0
0  9.976185e-01
1  1.930755e-03
2  2.716603e-04
3  1.636186e-04
4  1.543633e-05
5  5.294156e-33
6  2.963564e-34

# comments:
1. The pca(principle component analysis) is a machine learning algorithm helps to reduce dimensions.
2. pca calculate first covariance then calculates eigen values and eigen vectors to reduce dimensions.